<a href="https://colab.research.google.com/github/rahulde0/python-basics/blob/main/Python_Basics_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1D Array, 2D Array, 3D Array

In [1]:
# Creating 1D, 2D, and 3D NumPy arrays
import numpy as np
print("1 D Array")
array_1d = np.array([5,4,3,6,7,8,6,8,9])
print(array_1d[0])
print(array_1d[4])
print(array_1d[-1])
print(array_1d[2:5])
print(array_1d[:4])
print(array_1d[1:-1])
print(array_1d[-4:-1])
len(array_1d)
print(array_1d.sum())

print("2 D Array")
array_2d = np.array([[1,2,3,4], [5,6,7,8], [2,3,1,10]])
print(array_2d)
print(array_2d.shape) # 3rows, 4columns
print(array_2d[2][3])
print(array_2d[2,3])
print(array_2d[-2][-1])
print(array_2d[-2,-1])
print(array_2d[2][-1])
print(array_2d[:,2])
print(array_2d[1:-1,2])
print(array_2d[1:-1][0][2])
print(array_2d[1:-1,:-1])

print("\n3 D Array")
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[40, 50, 60], [70, 80, 30]],  [[41, 51, 61], [71, 81, 31]],  [[19, 29, 39], [49, 59, 69]]])
print(array_3d)
print(array_3d.shape)
print(array_3d[-1,-2,-2])
print(array_3d[2,1,1])
print(array_3d[1:,1:,1:])
print(array_3d[:-1,1:,:-1].shape)

1 D Array
5
7
9
[3 6 7]
[5 4 3 6]
[4 3 6 7 8 6 8]
[8 6 8]
56
2 D Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2  3  1 10]]
(3, 4)
10
10
8
8
10
[3 7 1]
[7]
7
[[5 6 7]]

3 D Array
[[[ 1  2  3]
  [ 4  5  6]]

 [[40 50 60]
  [70 80 30]]

 [[41 51 61]
  [71 81 31]]

 [[19 29 39]
  [49 59 69]]]
(4, 2, 3)
29
81
[[[80 30]]

 [[81 31]]

 [[59 69]]]
(3, 1, 2)
